export const ProductActions = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  INCREMENT: "INCREMENT",
  INCREMENT_SUCCESS: "INCREMENT_SUCCESS",
  DECREMENT: "DECREMENT",
  DECREMENT_SUCCESS: "DECREMENT_SUCCESS",
};
